//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;
using Travco.HIS.Model.Request.Reservation;

namespace Travco.HIS.Model.Request.DMG.Reservation
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class BOOKING
    {

        private HEADER hEADERField;

        private DATA_HOTEL[] dATA_HOTELField;

        private string typeField;

        private string langField;

        private BOOKINGNeedDTD needDTDField;

        private BOOKINGReturnURLNeed returnURLNeedField;

        private string returnURLField;

        private string aGENTCODEField;

        private string aGENTPASSWORDField;

        [XmlIgnore]
        public HISHeaderInfoRes HishHeaderInfo { get; set; }

        [XmlIgnore]
        public AdditionalInfoRes AdditionalInfo { get; set; }

        public BOOKING()
        {
            this.typeField = "HB";
            this.langField = "en-GB";
            this.needDTDField = BOOKINGNeedDTD.no;
            this.returnURLNeedField = BOOKINGReturnURLNeed.no;
        }

        /// <remarks/>
        public HEADER HEADER
        {
            get { return this.hEADERField; }
            set { this.hEADERField = value; }
        }

        public class AdditionalInfoRes
        {
            [XmlIgnore]
            public OTA_HotelResRQHotelReservationsHotelReservationRoomStay[] RoomStays { get; set; }

        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATA_HOTEL")]
        public DATA_HOTEL[] DATA_HOTEL
        {
            get { return this.dATA_HOTELField; }
            set { this.dATA_HOTELField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        //[System.ComponentModel.DefaultValueAttribute("en-GB")]
        public string lang
        {
            get { return this.langField; }
            set { this.langField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(BOOKINGNeedDTD.no)]
        public BOOKINGNeedDTD NeedDTD
        {
            get { return this.needDTDField; }
            set { this.needDTDField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(BOOKINGReturnURLNeed.no)]
        public BOOKINGReturnURLNeed returnURLNeed
        {
            get { return this.returnURLNeedField; }
            set { this.returnURLNeedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returnURL
        {
            get { return this.returnURLField; }
            set { this.returnURLField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AGENTCODE
        {
            get { return this.aGENTCODEField; }
            set { this.aGENTCODEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AGENTPASSWORD
        {
            get { return this.aGENTPASSWORDField; }
            set { this.aGENTPASSWORDField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class HEADER
    {

        private string iNTERNAL_CODE1Field;

        private string iNTERNAL_CODE2Field;

        private string iNTERNAL_CODE3Field;

        private string iNTERNAL_CODE4Field;

        private string iNTERNAL_CODE5Field;

        private string iNTERNAL_CODE6Field;

        private string iNTERNAL_CODE7Field;

        private string iNTERNAL_CODE8Field;

        private string iNTERNAL_CODE9Field;

        private HEADERNeedHotelMessages needHotelMessagesField;

        private string clerkCodeField;

        private string clerkPasswordField;

        public HEADER()
        {
            this.iNTERNAL_CODE1Field = "DWEBCN";
            this.iNTERNAL_CODE3Field = "";
            this.iNTERNAL_CODE5Field = "DWEBRS";
            this.iNTERNAL_CODE7Field = "1";
            this.iNTERNAL_CODE8Field = "VB";
            this.iNTERNAL_CODE9Field = "travel system";
            this.needHotelMessagesField = HEADERNeedHotelMessages.NO;
        }

        /// <remarks/>
        public string INTERNAL_CODE1
        {
            get { return this.iNTERNAL_CODE1Field; }
            set { this.iNTERNAL_CODE1Field = value; }
        }

        /// <remarks/>
        public string INTERNAL_CODE2
        {
            get { return this.iNTERNAL_CODE2Field; }
            set { this.iNTERNAL_CODE2Field = value; }
        }

        /// <remarks/>
        public string INTERNAL_CODE3
        {
            get { return this.iNTERNAL_CODE3Field; }
            set { this.iNTERNAL_CODE3Field = value; }
        }

        /// <remarks/>
        public string INTERNAL_CODE4
        {
            get { return this.iNTERNAL_CODE4Field; }
            set { this.iNTERNAL_CODE4Field = value; }
        }

        /// <remarks/>
        public string INTERNAL_CODE5
        {
            get { return this.iNTERNAL_CODE5Field; }
            set { this.iNTERNAL_CODE5Field = value; }
        }

        /// <remarks/>
        public string INTERNAL_CODE6
        {
            get { return this.iNTERNAL_CODE6Field; }
            set { this.iNTERNAL_CODE6Field = value; }
        }

        /// <remarks/>
        public string INTERNAL_CODE7
        {
            get { return this.iNTERNAL_CODE7Field; }
            set { this.iNTERNAL_CODE7Field = value; }
        }

        /// <remarks/>
        public string INTERNAL_CODE8
        {
            get { return this.iNTERNAL_CODE8Field; }
            set { this.iNTERNAL_CODE8Field = value; }
        }

        /// <remarks/>
        public string INTERNAL_CODE9
        {
            get { return this.iNTERNAL_CODE9Field; }
            set { this.iNTERNAL_CODE9Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(HEADERNeedHotelMessages.NO)]
        public HEADERNeedHotelMessages NeedHotelMessages
        {
            get { return this.needHotelMessagesField; }
            set { this.needHotelMessagesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClerkCode
        {
            get { return this.clerkCodeField; }
            set { this.clerkCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClerkPassword
        {
            get { return this.clerkPasswordField; }
            set { this.clerkPasswordField = value; }
        }
    }

    public class HISHeaderInfo:IHISHeaderInfo
    {
        [XmlIgnore]
        public EnvelopeHeader Header { get; set; }

        [XmlIgnore]
        public string RequestId { get; set; }

        [XmlIgnore]
        public string Transaction { get; set; }

        [XmlIgnore]
        public string EchoToken { get; set; }

        [XmlIgnore]
        public string Target { get; set; }

        [XmlIgnore]
        public string PrimaryLangID { get; set; }

    }

    public class HISHeaderInfoRes : HISHeaderInfo
    {
        [XmlIgnore]
        public EnvelopeHeader Header { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum HEADERNeedHotelMessages
    {

        /// <remarks/>
        YES,

        /// <remarks/>
        NO,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DATA_HOTEL
    {

        private string pAX_NAMEField;

        private string rEF_NOField;

        private string oUR_REF_NOField;

        private string cOMMENTSField;

        private string hOTEL_REQUESTField;

        private AGENT_COMMENTS aGENT_COMMENTSField;

        private bool aGENT_COMMENTSFieldSpecified;

        private DATA_SERVICE[] sERVICELISTField;

        private string aDULTSField;

        private string cHILDRENField;

        private string dURATIONField;

        private string aRR_DATEField;

        private string hOTEL_CODEField;

        private string rOOM_CODEField;

        private string sTATUSField;

        private string pRICE_CODEField;

        private string iNTERNAL_CODE10Field;

        private string iNFANTSField;

        private string iNTERNAL_CODE11Field;

        private string aRR_TRANS_NOField;

        private string aRR_FROMField;

        private string aRR_TOField;

        private string aRR_TIMEField;

        private string dEP_TRANS_NOField;

        private string dEP_FROMField;

        private string dEP_TOField;

        private string dEP_TIMEField;

        public DATA_HOTEL()
        {
            this.iNTERNAL_CODE10Field = "1";
            this.iNTERNAL_CODE11Field = "1";
        }

        /// <remarks/>
        public string PAX_NAME
        {
            get { return this.pAX_NAMEField; }
            set { this.pAX_NAMEField = value; }
        }

        /// <remarks/>
        public string REF_NO
        {
            get { return this.rEF_NOField; }
            set { this.rEF_NOField = value; }
        }

        /// <remarks/>
        public string OUR_REF_NO
        {
            get { return this.oUR_REF_NOField; }
            set { this.oUR_REF_NOField = value; }
        }

        /// <remarks/>
        public string COMMENTS
        {
            get { return this.cOMMENTSField; }
            set { this.cOMMENTSField = value; }
        }

        /// <remarks/>
        public string HOTEL_REQUEST
        {
            get { return this.hOTEL_REQUESTField; }
            set { this.hOTEL_REQUESTField = value; }
        }

        /// <remarks/>
        public AGENT_COMMENTS AGENT_COMMENTS
        {
            get { return this.aGENT_COMMENTSField; }
            set { this.aGENT_COMMENTSField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AGENT_COMMENTSSpecified
        {
            get { return this.aGENT_COMMENTSFieldSpecified; }
            set { this.aGENT_COMMENTSFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DATA_SERVICE", IsNullable = false)]
        public DATA_SERVICE[] SERVICELIST
        {
            get { return this.sERVICELISTField; }
            set { this.sERVICELISTField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string ADULTS
        {
            get { return this.aDULTSField; }
            set { this.aDULTSField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string CHILDREN
        {
            get { return this.cHILDRENField; }
            set { this.cHILDRENField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string DURATION
        {
            get { return this.dURATIONField; }
            set { this.dURATIONField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARR_DATE
        {
            get { return this.aRR_DATEField; }
            set { this.aRR_DATEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HOTEL_CODE
        {
            get { return this.hOTEL_CODEField; }
            set { this.hOTEL_CODEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ROOM_CODE
        {
            get { return this.rOOM_CODEField; }
            set { this.rOOM_CODEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string STATUS
        {
            get { return this.sTATUSField; }
            set { this.sTATUSField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PRICE_CODE
        {
            get { return this.pRICE_CODEField; }
            set { this.pRICE_CODEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INTERNAL_CODE10
        {
            get { return this.iNTERNAL_CODE10Field; }
            set { this.iNTERNAL_CODE10Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string INFANTS
        {
            get { return this.iNFANTSField; }
            set { this.iNFANTSField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INTERNAL_CODE11
        {
            get { return this.iNTERNAL_CODE11Field; }
            set { this.iNTERNAL_CODE11Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARR_TRANS_NO
        {
            get { return this.aRR_TRANS_NOField; }
            set { this.aRR_TRANS_NOField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARR_FROM
        {
            get { return this.aRR_FROMField; }
            set { this.aRR_FROMField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARR_TO
        {
            get { return this.aRR_TOField; }
            set { this.aRR_TOField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ARR_TIME
        {
            get { return this.aRR_TIMEField; }
            set { this.aRR_TIMEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DEP_TRANS_NO
        {
            get { return this.dEP_TRANS_NOField; }
            set { this.dEP_TRANS_NOField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DEP_FROM
        {
            get { return this.dEP_FROMField; }
            set { this.dEP_FROMField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DEP_TO
        {
            get { return this.dEP_TOField; }
            set { this.dEP_TOField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DEP_TIME
        {
            get { return this.dEP_TIMEField; }
            set { this.dEP_TIMEField = value; }
        }

        [XmlIgnore]
        public string RatePlanCode
        {
            get;set;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public enum AGENT_COMMENTS
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")] Item,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Must have hotel and room type requested")]
        Musthavehotelandroomtyperequested,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Alternative hotel of similar standard and price acceptable")]
        Alternativehotelofsimilarstandardandpriceacceptable,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DATA_SERVICE
    {

        private string sER_CODEField;

        private string sER_DATEField;

        private string sER_DURATIONField;

        private string sER_PAX_NOField;

        private string sER_STATUSField;

        private string sER_PRINCIPALField;

        private string sER_LOCATORField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SER_CODE
        {
            get { return this.sER_CODEField; }
            set { this.sER_CODEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SER_DATE
        {
            get { return this.sER_DATEField; }
            set { this.sER_DATEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string SER_DURATION
        {
            get { return this.sER_DURATIONField; }
            set { this.sER_DURATIONField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string SER_PAX_NO
        {
            get { return this.sER_PAX_NOField; }
            set { this.sER_PAX_NOField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SER_STATUS
        {
            get { return this.sER_STATUSField; }
            set { this.sER_STATUSField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SER_PRINCIPAL
        {
            get { return this.sER_PRINCIPALField; }
            set { this.sER_PRINCIPALField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SER_LOCATOR
        {
            get { return this.sER_LOCATORField; }
            set { this.sER_LOCATORField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum BOOKINGNeedDTD
    {

        /// <remarks/>
        yes,

        /// <remarks/>
        no,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum BOOKINGReturnURLNeed
    {

        /// <remarks/>
        yes,

        /// <remarks/>
        no,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SERVICELIST
    {

        private DATA_SERVICE[] dATA_SERVICEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATA_SERVICE")]
        public DATA_SERVICE[] DATA_SERVICE
        {
            get { return this.dATA_SERVICEField; }
            set { this.dATA_SERVICEField = value; }
        }
    }
}