//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace Travco.HIS.Data.Response.Reservation
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class RETURNDATA
    {

        private DATA_HOTEL[] dATA_HOTELField;

        private string typeField;

        private string langField;

        public RETURNDATA()
        {
            this.typeField = "HB";
        }

        /// <remarks/>
        [XmlElementAttribute("DATA_HOTEL")]
        public DATA_HOTEL[] DATA_HOTEL
        {
            get { return this.dATA_HOTELField; }
            set { this.dATA_HOTELField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string lang
        {
            get { return this.langField; }
            set { this.langField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DATA_HOTEL
    {

        private MESSAGE mESSAGEField;

        private string pAX_NAMEField;

        private string aGENTS_REF_NOField;

        private string rOOM_NAMEField;

        private string pRICE_DISPField;

        private string cURRENCY_NAMEField;

        private string hOTEL_REQUESTField;

        private string cOMMENTSField;

        private DATA_SERVICE[] sERVICELISTField;

        private DETAILS[] cHARGES_FOR_CANCELLATION_AMENDMENT_DONEField;

        private CANCELLATION_DETAILS[] fULL_CANCELLATION_DETAILSField;

        private HotelMessagesHotelMessage[] hotelMessagesField;

        private VoucherDetail voucherDetailField;

        private DATA_HOTELRatePlanDetails ratePlanDetailsField;

        private string hotelNameField;

        private string mainHotelNameField;

        private string tRAVCO_REF_NOField;

        private string aDULTSField;

        private string cHILDRENField;

        private string dURATIONField;

        private string aRR_DATEField;

        private string hOTEL_CODEField;

        private string rOOM_CODEField;

        private string sTATUSField;

        private string pRICE_CODEField;

        private string iNTERNAL_CODE1Field;

        private string iNFANTSField;

        private decimal aDULT_PRICEField;

        private bool aDULT_PRICEFieldSpecified;

        private decimal cHILD_PRICEField;

        private bool cHILD_PRICEFieldSpecified;

        private string cURR_CODEField;

        private string iNTERNAL_CODE2Field;

        private string aRR_TRANS_NOField;

        private string aRR_FROMField;

        private string aRR_TOField;

        private string aRR_TIMEField;

        private string dEP_TRANS_NOField;

        private string dEP_FROMField;

        private string dEP_TOField;

        private string dEP_TIMEField;

        private decimal tOTAL_PRICEField;

        private bool tOTAL_PRICEFieldSpecified;

        private string nO_OF_ROOMSField;

        private string mainHotelCodeField;

        public DATA_HOTEL()
        {
            this.iNTERNAL_CODE1Field = "1";
            this.iNTERNAL_CODE2Field = "1";
        }

        /// <remarks/>
        public MESSAGE MESSAGE
        {
            get { return this.mESSAGEField; }
            set { this.mESSAGEField = value; }
        }

        /// <remarks/>
        public string PAX_NAME
        {
            get { return this.pAX_NAMEField; }
            set { this.pAX_NAMEField = value; }
        }

        /// <remarks/>
        public string AGENTS_REF_NO
        {
            get { return this.aGENTS_REF_NOField; }
            set { this.aGENTS_REF_NOField = value; }
        }

        /// <remarks/>
        public string ROOM_NAME
        {
            get { return this.rOOM_NAMEField; }
            set { this.rOOM_NAMEField = value; }
        }

        /// <remarks/>
        public string PRICE_DISP
        {
            get { return this.pRICE_DISPField; }
            set { this.pRICE_DISPField = value; }
        }

        /// <remarks/>
        public string CURRENCY_NAME
        {
            get { return this.cURRENCY_NAMEField; }
            set { this.cURRENCY_NAMEField = value; }
        }

        /// <remarks/>
        public string HOTEL_REQUEST
        {
            get { return this.hOTEL_REQUESTField; }
            set { this.hOTEL_REQUESTField = value; }
        }

        /// <remarks/>
        public string COMMENTS
        {
            get { return this.cOMMENTSField; }
            set { this.cOMMENTSField = value; }
        }

        /// <remarks/>
        [XmlArrayItemAttribute("DATA_SERVICE", IsNullable = false)]
        public DATA_SERVICE[] SERVICELIST
        {
            get { return this.sERVICELISTField; }
            set { this.sERVICELISTField = value; }
        }

        /// <remarks/>
        [XmlArrayItemAttribute("DETAILS", IsNullable = false)]
        public DETAILS[] CHARGES_FOR_CANCELLATION_AMENDMENT_DONE
        {
            get { return this.cHARGES_FOR_CANCELLATION_AMENDMENT_DONEField; }
            set { this.cHARGES_FOR_CANCELLATION_AMENDMENT_DONEField = value; }
        }

        /// <remarks/>
        [XmlArrayItemAttribute("CANCELLATION_DETAILS", IsNullable = false)]
        public CANCELLATION_DETAILS[] FULL_CANCELLATION_DETAILS
        {
            get { return this.fULL_CANCELLATION_DETAILSField; }
            set { this.fULL_CANCELLATION_DETAILSField = value; }
        }

        /// <remarks/>
        [XmlArrayItemAttribute("HotelMessage",
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public HotelMessagesHotelMessage[] HotelMessages
        {
            get { return this.hotelMessagesField; }
            set { this.hotelMessagesField = value; }
        }

        /// <remarks/>
        public VoucherDetail VoucherDetail
        {
            get { return this.voucherDetailField; }
            set { this.voucherDetailField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DATA_HOTELRatePlanDetails RatePlanDetails
        {
            get { return this.ratePlanDetailsField; }
            set { this.ratePlanDetailsField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HotelName
        {
            get { return this.hotelNameField; }
            set { this.hotelNameField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MainHotelName
        {
            get { return this.mainHotelNameField; }
            set { this.mainHotelNameField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string TRAVCO_REF_NO
        {
            get { return this.tRAVCO_REF_NOField; }
            set { this.tRAVCO_REF_NOField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "integer")]
        public string ADULTS
        {
            get { return this.aDULTSField; }
            set { this.aDULTSField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "integer")]
        public string CHILDREN
        {
            get { return this.cHILDRENField; }
            set { this.cHILDRENField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "integer")]
        public string DURATION
        {
            get { return this.dURATIONField; }
            set { this.dURATIONField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ARR_DATE
        {
            get { return this.aRR_DATEField; }
            set { this.aRR_DATEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string HOTEL_CODE
        {
            get { return this.hOTEL_CODEField; }
            set { this.hOTEL_CODEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ROOM_CODE
        {
            get { return this.rOOM_CODEField; }
            set { this.rOOM_CODEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string STATUS
        {
            get { return this.sTATUSField; }
            set { this.sTATUSField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string PRICE_CODE
        {
            get { return this.pRICE_CODEField; }
            set { this.pRICE_CODEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string INTERNAL_CODE1
        {
            get { return this.iNTERNAL_CODE1Field; }
            set { this.iNTERNAL_CODE1Field = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "integer")]
        public string INFANTS
        {
            get { return this.iNFANTSField; }
            set { this.iNFANTSField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public decimal ADULT_PRICE
        {
            get { return this.aDULT_PRICEField; }
            set { this.aDULT_PRICEField = value; }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool ADULT_PRICESpecified
        {
            get { return this.aDULT_PRICEFieldSpecified; }
            set { this.aDULT_PRICEFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public decimal CHILD_PRICE
        {
            get { return this.cHILD_PRICEField; }
            set { this.cHILD_PRICEField = value; }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool CHILD_PRICESpecified
        {
            get { return this.cHILD_PRICEFieldSpecified; }
            set { this.cHILD_PRICEFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string CURR_CODE
        {
            get { return this.cURR_CODEField; }
            set { this.cURR_CODEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string INTERNAL_CODE2
        {
            get { return this.iNTERNAL_CODE2Field; }
            set { this.iNTERNAL_CODE2Field = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ARR_TRANS_NO
        {
            get { return this.aRR_TRANS_NOField; }
            set { this.aRR_TRANS_NOField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ARR_FROM
        {
            get { return this.aRR_FROMField; }
            set { this.aRR_FROMField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ARR_TO
        {
            get { return this.aRR_TOField; }
            set { this.aRR_TOField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ARR_TIME
        {
            get { return this.aRR_TIMEField; }
            set { this.aRR_TIMEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string DEP_TRANS_NO
        {
            get { return this.dEP_TRANS_NOField; }
            set { this.dEP_TRANS_NOField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string DEP_FROM
        {
            get { return this.dEP_FROMField; }
            set { this.dEP_FROMField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string DEP_TO
        {
            get { return this.dEP_TOField; }
            set { this.dEP_TOField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string DEP_TIME
        {
            get { return this.dEP_TIMEField; }
            set { this.dEP_TIMEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public decimal TOTAL_PRICE
        {
            get { return this.tOTAL_PRICEField; }
            set { this.tOTAL_PRICEField = value; }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool TOTAL_PRICESpecified
        {
            get { return this.tOTAL_PRICEFieldSpecified; }
            set { this.tOTAL_PRICEFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string NO_OF_ROOMS
        {
            get { return this.nO_OF_ROOMSField; }
            set { this.nO_OF_ROOMSField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string MainHotelCode
        {
            get { return this.mainHotelCodeField; }
            set { this.mainHotelCodeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class MESSAGE
    {

        private string eRROR_DESCRIPTIONField;

        private string eRROR_CODEField;

        /// <remarks/>
        public string ERROR_DESCRIPTION
        {
            get { return this.eRROR_DESCRIPTIONField; }
            set { this.eRROR_DESCRIPTIONField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ERROR_CODE
        {
            get { return this.eRROR_CODEField; }
            set { this.eRROR_CODEField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DATA_SERVICE
    {

        private string sER_PRICEField;

        private string sER_CODEField;

        private string sER_DATEField;

        private string sER_DURATIONField;

        private string sER_PAX_NOField;

        private string sER_PRINCIPALField;

        private string sER_LOCATORField;

        /// <remarks/>
        public string SER_PRICE
        {
            get { return this.sER_PRICEField; }
            set { this.sER_PRICEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string SER_CODE
        {
            get { return this.sER_CODEField; }
            set { this.sER_CODEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string SER_DATE
        {
            get { return this.sER_DATEField; }
            set { this.sER_DATEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "integer")]
        public string SER_DURATION
        {
            get { return this.sER_DURATIONField; }
            set { this.sER_DURATIONField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute(DataType = "integer")]
        public string SER_PAX_NO
        {
            get { return this.sER_PAX_NOField; }
            set { this.sER_PAX_NOField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string SER_PRINCIPAL
        {
            get { return this.sER_PRINCIPALField; }
            set { this.sER_PRINCIPALField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string SER_LOCATOR
        {
            get { return this.sER_LOCATORField; }
            set { this.sER_LOCATORField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DETAILS
    {

        private string[] cANCELLATION_POLICYField;

        private string cANCELLATION_DATEField;

        private string cANCELLATION_TIMEField;

        private string tOTAL_CANCELLATION_FEEField;

        private string hOTEL_DEADLINEField;

        /// <remarks/>
        [XmlElementAttribute("CANCELLATION_POLICY")]
        public string[] CANCELLATION_POLICY
        {
            get { return this.cANCELLATION_POLICYField; }
            set { this.cANCELLATION_POLICYField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string CANCELLATION_DATE
        {
            get { return this.cANCELLATION_DATEField; }
            set { this.cANCELLATION_DATEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string CANCELLATION_TIME
        {
            get { return this.cANCELLATION_TIMEField; }
            set { this.cANCELLATION_TIMEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string TOTAL_CANCELLATION_FEE
        {
            get { return this.tOTAL_CANCELLATION_FEEField; }
            set { this.tOTAL_CANCELLATION_FEEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string HOTEL_DEADLINE
        {
            get { return this.hOTEL_DEADLINEField; }
            set { this.hOTEL_DEADLINEField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CANCELLATION_DETAILS
    {

        private string[] cANCELLATION_CHARGEField;

        private string lAST_POSSIBLE_CANCELLATION_DATEField;

        private string tIME_BEFOREField;

        /// <remarks/>
        [XmlElementAttribute("CANCELLATION_CHARGE")]
        public string[] CANCELLATION_CHARGE
        {
            get { return this.cANCELLATION_CHARGEField; }
            set { this.cANCELLATION_CHARGEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string LAST_POSSIBLE_CANCELLATION_DATE
        {
            get { return this.lAST_POSSIBLE_CANCELLATION_DATEField; }
            set { this.lAST_POSSIBLE_CANCELLATION_DATEField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string TIME_BEFORE
        {
            get { return this.tIME_BEFOREField; }
            set { this.tIME_BEFOREField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public partial class HotelMessagesHotelMessage
    {

        private string hotelMessageTextField;

        private string hotelMessageCodeField;

        private string fromDateField;

        private string toDateField;

        private HotelMessagesHotelMessageMessageIndicator messageIndicatorField;

        private bool messageIndicatorFieldSpecified;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HotelMessageText
        {
            get { return this.hotelMessageTextField; }
            set { this.hotelMessageTextField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string HotelMessageCode
        {
            get { return this.hotelMessageCodeField; }
            set { this.hotelMessageCodeField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string FromDate
        {
            get { return this.fromDateField; }
            set { this.fromDateField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ToDate
        {
            get { return this.toDateField; }
            set { this.toDateField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public HotelMessagesHotelMessageMessageIndicator MessageIndicator
        {
            get { return this.messageIndicatorField; }
            set { this.messageIndicatorField = value; }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool MessageIndicatorSpecified
        {
            get { return this.messageIndicatorFieldSpecified; }
            set { this.messageIndicatorFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlTypeAttribute(AnonymousType = true)]
    public enum HotelMessagesHotelMessageMessageIndicator
    {

        /// <remarks/>
        Block,

        /// <remarks/>
        Information,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class VoucherDetail
    {

        private string hotelNameField;

        private string hotelAddressField;

        private string hotelPostalCodeField;

        private string hotelTelNoField;

        private string hotelFaxNoField;

        private string hotelEmailAddressField;

        private string customerEmailAddressesField;

        private string agentReferenceField;

        private string voucherNoField;

        private string bookingDateField;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HotelName
        {
            get { return this.hotelNameField; }
            set { this.hotelNameField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HotelAddress
        {
            get { return this.hotelAddressField; }
            set { this.hotelAddressField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HotelPostalCode
        {
            get { return this.hotelPostalCodeField; }
            set { this.hotelPostalCodeField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HotelTelNo
        {
            get { return this.hotelTelNoField; }
            set { this.hotelTelNoField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HotelFaxNo
        {
            get { return this.hotelFaxNoField; }
            set { this.hotelFaxNoField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HotelEmailAddress
        {
            get { return this.hotelEmailAddressField; }
            set { this.hotelEmailAddressField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerEmailAddresses
        {
            get { return this.customerEmailAddressesField; }
            set { this.customerEmailAddressesField = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AgentReference
        {
            get { return this.agentReferenceField; }
            set { this.agentReferenceField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string VoucherNo
        {
            get { return this.voucherNoField; }
            set { this.voucherNoField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string BookingDate
        {
            get { return this.bookingDateField; }
            set { this.bookingDateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public partial class DATA_HOTELRatePlanDetails
    {

        private string ratePlanDescriptionField;

        private string ratePlanCodeField;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RatePlanDescription
        {
            get { return this.ratePlanDescriptionField; }
            set { this.ratePlanDescriptionField = value; }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string RatePlanCode
        {
            get { return this.ratePlanCodeField; }
            set { this.ratePlanCodeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SERVICELIST
    {

        private DATA_SERVICE[] dATA_SERVICEField;

        /// <remarks/>
        [XmlElementAttribute("DATA_SERVICE")]
        public DATA_SERVICE[] DATA_SERVICE
        {
            get { return this.dATA_SERVICEField; }
            set { this.dATA_SERVICEField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CHARGES_FOR_CANCELLATION_AMENDMENT_DONE
    {

        private DETAILS[] dETAILSField;

        /// <remarks/>
        [XmlElementAttribute("DETAILS")]
        public DETAILS[] DETAILS
        {
            get { return this.dETAILSField; }
            set { this.dETAILSField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class FULL_CANCELLATION_DETAILS
    {

        private CANCELLATION_DETAILS[] cANCELLATION_DETAILSField;

        /// <remarks/>
        [XmlElementAttribute("CANCELLATION_DETAILS")]
        public CANCELLATION_DETAILS[] CANCELLATION_DETAILS
        {
            get { return this.cANCELLATION_DETAILSField; }
            set { this.cANCELLATION_DETAILSField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class HotelMessages
    {

        private HotelMessagesHotelMessage[] hotelMessageField;

        /// <remarks/>
        [XmlElementAttribute("HotelMessage", Form =
            System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HotelMessagesHotelMessage[] HotelMessage
        {
            get { return this.hotelMessageField; }
            set { this.hotelMessageField = value; }
        }
    }
}